import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Munish&apos;s</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="theme-color" content="#000000"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <div>
                    </div>
                </div>
            
                <div className={styles.center}>
                    <div className='flex flex-col'>
                        <div className={`${inter.className} font-semibold text-md mb-2`}>Hey! Check back soon.</div>
                        <div className={`${inter.className} font-bold text-2xl`}>
                            We are under maintenance.
                        </div>

                    </div>
                </div>

                <div className={styles.grid}>
                    <a
                        href="https://github.com/munish-codes"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            GitHub <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            github.com/munish.codes
                        </p>
                    </a>

                    <a
                        href="https://linkedin.com/in/munish-codes"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            LinkedIn <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            linkedin.com/in/munish-codes
                        </p>
                    </a>

                    <a
                        href="https://instagram.com/munish.codes"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Instagram <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            instagram.com/munish.codes
                        </p>
                    </a>

                    <a
                        href="mailto:hello@munish.dev"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Email <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            hello@munish.dev
                        </p>
                    </a>
                </div>

            </main>
        </>
    )
}
